version: '3.6'
services:
  postgres:
    build: ./postgres
    environment:
    - POSTGRES_DB=docker
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
    restart: always
    volumes:
    - ./db_data:/var/lib/postgresql/data
    ports: ["5432:5432"]
  graphql-engine:
    image: hasura/graphql-engine:v1.2.2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://docker:docker@postgres:5432/docker
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${GRAPHQL_KEY}
  frontend:
    build:
      context: ${FRONTEND_DIRECTORY}
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    restart: always
       
volumes:
  db_data:
