FROM ocaml/opam:debian-11-ocaml-4.14 AS build

RUN sudo apt-get update && \
    sudo apt-get install -qq -yy \
    pkg-config \
    m4 \
    libssl-dev \
    libsqlite3-dev \
    libpq-dev \
    libgmp-dev \
    libffi-dev \
    libev-dev \
    libcapnp-dev \
    graphviz \
    capnproto

RUN opam remote add origin 'https://opam.ocaml.org' --all-switches && opam remote remove default && opam update

WORKDIR /mnt/project

# Build dependencies.
COPY --chown=opam:opam pipeline/pipeline.opam pipeline.opam
RUN opam install -y --deps-only -t .

USER root

ARG TARGET_ARCH=amd64

RUN apt-get update \
    && apt-get install --no-install-recommends --assume-yes \
    netbase \
    ca-certificates \
    apt-transport-https \
    curl \
    netcat \
    postgresql-client \
    gnupg \
    lsb-release \
    git \
    libpq-dev \
    libsqlite3-dev \
    libev-dev \
    inotify-tools \
    procps \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    && echo "deb [arch=${TARGET_ARCH} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list \
    && ( curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc > /etc/apt/trusted.gpg.d/ngrok.asc ) \
    && ( echo "deb https://ngrok-agent.s3.amazonaws.com buster main" > /etc/apt/sources.list.d/ngrok.list ) \
    && apt-get update \
    && apt-get install docker-ce-cli graphviz ngrok --assume-yes \
    && rm -r /var/lib/apt/lists /var/cache/apt

COPY --chown=opam:opam pipeline/. .

# Build the project.
RUN opam exec -- dune build --profile=release bin/main.exe

WORKDIR /app

RUN mkdir bin
ENV PATH="/app/bin:${PATH}"

COPY environments/ /mnt/environments/
COPY pipeline/aslr_seccomp.json /app/aslr_seccomp.json
COPY pipeline/db/migrations /app/db/migrations
RUN cp /home/opam/.opam/4.14/bin/omigrate /app/bin/omigrate
RUN cp /home/opam/.opam/4.14/bin/ocluster-admin /app/bin/ocluster-admin
RUN cp /mnt/project/_build/default/bin/main.exe /app/bin/current-bench-pipeline
COPY pipeline/entrypoint.sh /app/entrypoint.sh
