name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.12.0
          - 4.11.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1.1.10
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: sudo apt-get install -y capnproto graphviz libcapnp-dev

      - run: opam install ./pipeline/ --deps-only --yes --with-test

      - run: opam exec -- dune build ./pipeline/bin/main.exe --profile=release
